# .bashrc

if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

export JAVA_HOME=/usr/lib/jvm/java
export HADOOP_HOME=/opt/hadoop
export HADOOP_BIN=$HADOOP_HOME/bin
export HADOOP_SBIN=$HADOOP_HOME/sbin
export HADOOP_COMMON_LIB_NATIVE_DIR=${HADOOP_HOME}/lib/native
export HADOOP_OPTS="-Djava.library.path=${HADOOP_HOME}/lib"
export PATH=$PATH:$HADOOP_BIN:$HADOOP_SBIN
