# .bashrc

if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
export HADOOP_HOME=/opt/hadoop
export SPARK_HOME=/opt/spark
export SPARK_BIN=$SPARK_HOME/bin
export HADOOP_BIN=$HADOOP_HOME/bin
export SPARK_SBIN=$SPARK_HOME/sbin
export PATH=$PATH:$SPARK_BIN:$SPARK_SBIN:$HADOOP_BIN
